version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
    
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend